site_name: LibreIncu
site_description: 'Documentación LibreIncu'
site_author: 'AlterMundi-CTO'
docs_dir: docs/
repo_url: 'https://github.com/AlterMundi-MonitoreoyControl/website'
theme: 
  favicon: img/favicon.ico
  name: material
  logo: img/logo.png
  palette:
    scheme: slate
    primary: green 
    
     
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  